### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by VisImage** [Soham-Deshpande/Stock-TFT#11]
It seems to be a great writing. please let me know how to run the code. Trying to use the repository as follows
1. pip install -r requirements.txt : executed without problem!
2.  run main.py: does not work

**Comment by Soham-Deshpande** [comment]
My bad, I believe the file that should actually be run is PytorchForecasting.py. Hope this works and feel free to ask if you want clarification on anything!

**Comment by VisImage** [comment]
Would you please tell where is "PytorchForecasting.py" located?

**Comment by Soham-Deshpande** [comment]
> Would you please tell where is "PytorchForecasting.py" located?

It's in Code/'TFT Model'/PytorchForecasting.py
